"""Auto-generated test cases.

248 functions, 964 test cases.
"""

TESTS_AUTO = {
    'all_path_sums': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'all_positive': [
        {'args': ('',), 'expected': True},
        {'args': ([1, 2, 3],), 'expected': True},
        {'args': ([],), 'expected': True},
    ],
    'all_true': [
        {'args': ('hello',), 'expected': True},
        {'args': ('',), 'expected': True},
        {'args': ([1, 2, 3],), 'expected': True},
        {'args': ([],), 'expected': True},
    ],
    'all_unique': [
        {'args': ('hello',), 'expected': False},
        {'args': ('',), 'expected': True},
        {'args': ([1, 2, 3],), 'expected': True},
        {'args': ([],), 'expected': True},
    ],
    'any_negative': [
        {'args': ('',), 'expected': False},
        {'args': ([1, 2, 3],), 'expected': False},
        {'args': ([],), 'expected': False},
    ],
    'any_true': [
        {'args': ('hello',), 'expected': True},
        {'args': ('',), 'expected': False},
        {'args': ([1, 2, 3],), 'expected': True},
        {'args': ([],), 'expected': False},
    ],
    'argmax': [
        {'args': (0,), 'expected': -1},
        {'args': ('hello',), 'expected': 4},
        {'args': ('',), 'expected': -1},
        {'args': ([1, 2, 3],), 'expected': 2},
        {'args': ([],), 'expected': -1},
    ],
    'argmin': [
        {'args': (0,), 'expected': -1},
        {'args': ('hello',), 'expected': 1},
        {'args': ('',), 'expected': -1},
        {'args': ([1, 2, 3],), 'expected': 0},
        {'args': ([],), 'expected': -1},
    ],
    'atbash': [
        {'args': ('hello',), 'expected': 'svool'},
        {'args': ('',), 'expected': ''},
        {'args': ([],), 'expected': ''},
    ],
    'between': [
        {'args': (1, 2, 3), 'expected': False},
        {'args': (0, 0, 0), 'expected': True},
        {'args': (5, 3, 1), 'expected': False},
        {'args': (10, 2, 8), 'expected': False},
    ],
    'bitonic_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'bst_from_sorted': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'bst_level_max': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'bst_level_min': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'bst_max': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'bst_max_path_sum': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'bst_min': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'bst_min_path_sum': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'bst_sum_left_leaves': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'bst_sum_of_depths': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'bst_sum_of_left_leaves': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'bst_sum_right_leaves': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'bst_sum_root_to_leaf': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'bst_to_sorted_list': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'bubble_sort_optimized': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'bucket_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'catalan': [
        {'args': (0,), 'expected': 1},
        {'args': (1,), 'expected': 1},
        {'args': (5,), 'expected': 42},
    ],
    'circle_circumference': [
        {'args': (0,), 'expected': 0.0, 'approx': True},
        {'args': (1,), 'expected': 6.283185307179586, 'approx': True},
        {'args': (-1,), 'expected': -6.283185307179586, 'approx': True},
        {'args': (5,), 'expected': 31.41592653589793, 'approx': True},
    ],
    'clamp': [
        {'args': (1, 2, 3), 'expected': 2},
        {'args': (0, 0, 0), 'expected': 0},
        {'args': (5, 3, 1), 'expected': 3},
        {'args': (10, 2, 8), 'expected': 8},
    ],
    'cocktail_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'comb_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'compare_strings': [
        {'args': (0, 0), 'expected': 0},
        {'args': (1, 1), 'expected': 0},
        {'args': (2, 3), 'expected': -1},
        {'args': (5, 2), 'expected': 1},
        {'args': ('a', 'b'), 'expected': -1},
    ],
    'concat_lists': [
        {'args': (0, 0), 'expected': 0},
        {'args': (1, 1), 'expected': 2},
        {'args': (2, 3), 'expected': 5},
        {'args': (5, 2), 'expected': 7},
        {'args': ('a', 'b'), 'expected': 'ab'},
    ],
    'contains': [
        {'args': ('a', 'b'), 'expected': False},
        {'args': ('hello', 'world'), 'expected': False},
        {'args': ([1, 2], [3, 4]), 'expected': False},
        {'args': ([], []), 'expected': False},
    ],
    'contains_duplicate': [
        {'args': ('hello',), 'expected': True},
        {'args': ('',), 'expected': False},
        {'args': ([1, 2, 3],), 'expected': False},
        {'args': ([],), 'expected': False},
    ],
    'count_false': [
        {'args': ('hello',), 'expected': 0},
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 0},
        {'args': ([],), 'expected': 0},
    ],
    'count_lines': [
        {'args': (0,), 'expected': 0},
        {'args': ('hello',), 'expected': 1},
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': 0},
    ],
    'count_lower': [
        {'args': ('hello',), 'expected': 5},
        {'args': ('',), 'expected': 0},
        {'args': ([],), 'expected': 0},
    ],
    'count_occurrences': [
        {'args': ('a', 'b'), 'expected': 0},
        {'args': ('hello', 'world'), 'expected': 0},
        {'args': ([1, 2], [3, 4]), 'expected': 0},
        {'args': ([], []), 'expected': 0},
    ],
    'count_special': [
        {'args': ('hello',), 'expected': 0},
        {'args': ('',), 'expected': 0},
        {'args': ([],), 'expected': 0},
    ],
    'count_substring': [
        {'args': ('a', 'b'), 'expected': 0},
        {'args': ('hello', 'world'), 'expected': 0},
        {'args': ([1, 2], [3, 4]), 'expected': 0},
        {'args': ([], []), 'expected': 0},
    ],
    'count_true': [
        {'args': ('hello',), 'expected': 5},
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': 0},
    ],
    'count_upper': [
        {'args': ('hello',), 'expected': 0},
        {'args': ('',), 'expected': 0},
        {'args': ([],), 'expected': 0},
    ],
    'count_words': [
        {'args': ('hello',), 'expected': 1},
        {'args': ('',), 'expected': 0},
    ],
    'count_words_file': [
        {'args': ('hello',), 'expected': 1},
        {'args': ('',), 'expected': 0},
    ],
    'counting_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'counting_sort_stable': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'cube_volume': [
        {'args': (0,), 'expected': 0},
        {'args': (1,), 'expected': 1},
        {'args': (-1,), 'expected': -1},
        {'args': (5,), 'expected': 125},
    ],
    'cumulative_sum': [
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 3, 6]},
        {'args': ([],), 'expected': []},
    ],
    'cycle_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'determinant_2x2': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'determinant_3x3': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'diff_list': [
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 1]},
        {'args': ([],), 'expected': []},
    ],
    'distance': [
        {'args': (1, 2, 3, 4), 'expected': 2.8284271247461903, 'approx': True},
        {'args': (0, 0, 0, 0), 'expected': 0.0, 'approx': True},
    ],
    'doubly_linked_reverse': [
        {'args': ('hello',), 'expected': 'olleh'},
        {'args': ('',), 'expected': ''},
        {'args': ([1, 2, 3],), 'expected': [3, 2, 1]},
        {'args': ([],), 'expected': []},
    ],
    'dp_max_product_subarray': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'dp_min_cost_climbing': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'dp_min_path_sum': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'ends_with': [
        {'args': ('a', 'b'), 'expected': False},
        {'args': ('hello', 'world'), 'expected': False},
    ],
    'farewell': [
        {'args': ('hello',), 'expected': 'Goodbye, hello!'},
        {'args': ('',), 'expected': 'Goodbye, !'},
    ],
    'fibonacci': [
        {'args': (0,), 'expected': 0},
        {'args': (1,), 'expected': 1},
        {'args': (-1,), 'expected': 0},
        {'args': (5,), 'expected': 5},
    ],
    'filter_even': [
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [2]},
        {'args': ([],), 'expected': []},
    ],
    'filter_negative': [
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': []},
        {'args': ([],), 'expected': []},
    ],
    'filter_odd': [
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 3]},
        {'args': ([],), 'expected': []},
    ],
    'filter_positive': [
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'find_second_max': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'find_second_min': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'first_char': [
        {'args': (0,), 'expected': ''},
        {'args': ('hello',), 'expected': 'h'},
        {'args': ('',), 'expected': ''},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': ''},
    ],
    'first_element': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'h'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'first_index': [
        {'args': ('a', 'b'), 'expected': -1},
        {'args': ('hello', 'world'), 'expected': -1},
        {'args': ([1, 2], [3, 4]), 'expected': -1},
        {'args': ([], []), 'expected': -1},
    ],
    'first_unique': [
        {'args': ('hello',), 'expected': 0},
        {'args': ('',), 'expected': -1},
        {'args': ([1, 2, 3],), 'expected': 0},
        {'args': ([],), 'expected': -1},
    ],
    'first_word': [
        {'args': ('hello',), 'expected': 'hello'},
        {'args': ('',), 'expected': ''},
    ],
    'gaussian_elimination': [
        {'args': (0, 0), 'expected': 0},
        {'args': (1, 1), 'expected': 1},
        {'args': (2, 3), 'expected': 2},
        {'args': (5, 2), 'expected': 2},
        {'args': ('a', 'b'), 'expected': 'a'},
    ],
    'get_alpha': [
        {'args': ('hello',), 'expected': 'hello'},
        {'args': ('',), 'expected': ''},
        {'args': ([],), 'expected': ''},
    ],
    'get_digits': [
        {'args': ('hello',), 'expected': ''},
        {'args': ('',), 'expected': ''},
        {'args': ([],), 'expected': ''},
    ],
    'get_unique_chars': [
        {'args': ('hello',), 'expected': ['h', 'e', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'get_words': [
        {'args': ('hello',), 'expected': ['hello']},
        {'args': ('',), 'expected': []},
    ],
    'gnome_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'graph_topological_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'graph_topological_sort_dfs': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'graph_topological_sort_kahn': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'heap_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'heap_sort_max': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'heap_sort_min': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'in_range': [
        {'args': (1, 2, 3), 'expected': False},
        {'args': (0, 0, 0), 'expected': True},
        {'args': (5, 3, 1), 'expected': False},
        {'args': (10, 2, 8), 'expected': False},
    ],
    'insertion_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'insertion_sort_binary': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'interleave': [
        {'args': ('a', 'b'), 'expected': ['a', 'b']},
        {'args': ('hello', 'world'), 'expected': ['h', 'w', 'e', 'o', 'l', 'r', 'l', 'l', 'o', 'd']},
        {'args': ([1, 2], [3, 4]), 'expected': [1, 3, 2, 4]},
        {'args': ([], []), 'expected': []},
    ],
    'introsort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'invert_bool': [
        {'args': (0,), 'expected': True},
        {'args': (1,), 'expected': False},
        {'args': (-1,), 'expected': False},
        {'args': (5,), 'expected': False},
        {'args': ('hello',), 'expected': False},
    ],
    'is_alpha': [
        {'args': ('hello',), 'expected': True},
        {'args': ('',), 'expected': False},
    ],
    'is_armstrong': [
        {'args': (0,), 'expected': True},
        {'args': (1,), 'expected': True},
        {'args': (5,), 'expected': True},
        {'args': ('',), 'expected': False},
    ],
    'is_coprime': [
        {'args': (0, 0), 'expected': False},
        {'args': (1, 1), 'expected': True},
        {'args': (2, 3), 'expected': True},
        {'args': (5, 2), 'expected': True},
    ],
    'is_digit': [
        {'args': ('hello',), 'expected': False},
        {'args': ('',), 'expected': False},
    ],
    'is_disjoint': [
        {'args': ('a', 'b'), 'expected': True},
        {'args': ('hello', 'world'), 'expected': False},
        {'args': ([1, 2], [3, 4]), 'expected': True},
        {'args': ([], []), 'expected': True},
    ],
    'is_empty': [
        {'args': ('hello',), 'expected': False},
        {'args': ('',), 'expected': True},
        {'args': ([1, 2, 3],), 'expected': False},
        {'args': ([],), 'expected': True},
    ],
    'is_empty_list': [
        {'args': ('hello',), 'expected': False},
        {'args': ('',), 'expected': True},
        {'args': ([1, 2, 3],), 'expected': False},
        {'args': ([],), 'expected': True},
    ],
    'is_fibonacci': [
        {'args': (0,), 'expected': True},
        {'args': (1,), 'expected': True},
        {'args': (-1,), 'expected': False},
        {'args': (5,), 'expected': True},
    ],
    'is_greater_equal': [
        {'args': (0, 0), 'expected': True},
        {'args': (1, 1), 'expected': True},
        {'args': (2, 3), 'expected': False},
        {'args': (5, 2), 'expected': False},
        {'args': ('a', 'b'), 'expected': False},
    ],
    'is_less': [
        {'args': (0, 0), 'expected': False},
        {'args': (1, 1), 'expected': False},
        {'args': (2, 3), 'expected': True},
        {'args': (5, 2), 'expected': False},
        {'args': ('a', 'b'), 'expected': True},
    ],
    'is_less_equal': [
        {'args': (0, 0), 'expected': True},
        {'args': (1, 1), 'expected': True},
        {'args': (2, 3), 'expected': False},
        {'args': (5, 2), 'expected': False},
        {'args': ('a', 'b'), 'expected': False},
    ],
    'is_lower': [
        {'args': ('hello',), 'expected': True},
        {'args': ('',), 'expected': False},
    ],
    'is_narcissistic': [
        {'args': (0,), 'expected': True},
        {'args': (1,), 'expected': True},
        {'args': (5,), 'expected': True},
        {'args': ('',), 'expected': False},
    ],
    'is_nonnegative': [
        {'args': (0,), 'expected': False},
        {'args': (1,), 'expected': False},
        {'args': (-1,), 'expected': True},
        {'args': (5,), 'expected': False},
    ],
    'is_nonpositive': [
        {'args': (0,), 'expected': False},
        {'args': (1,), 'expected': True},
        {'args': (-1,), 'expected': False},
        {'args': (5,), 'expected': True},
    ],
    'is_nonzero': [
        {'args': (0,), 'expected': True},
        {'args': (1,), 'expected': False},
        {'args': (-1,), 'expected': False},
        {'args': (5,), 'expected': False},
        {'args': ('hello',), 'expected': False},
    ],
    'is_not_equal': [
        {'args': (0, 0), 'expected': True},
        {'args': (1, 1), 'expected': True},
        {'args': (2, 3), 'expected': False},
        {'args': (5, 2), 'expected': False},
        {'args': ('a', 'b'), 'expected': False},
    ],
    'is_palindrome_list': [
        {'args': ('hello',), 'expected': False},
        {'args': ('',), 'expected': True},
        {'args': ([1, 2, 3],), 'expected': False},
        {'args': ([],), 'expected': True},
    ],
    'is_palindrome_rec': [
        {'args': (0,), 'expected': True},
        {'args': (1,), 'expected': True},
        {'args': (-1,), 'expected': False},
        {'args': (5,), 'expected': True},
        {'args': ('hello',), 'expected': False},
    ],
    'is_perfect_cube': [
        {'args': (0,), 'expected': True},
        {'args': (1,), 'expected': True},
        {'args': (5,), 'expected': False},
    ],
    'is_prime_simple': [
        {'args': (0,), 'expected': False},
        {'args': (1,), 'expected': False},
        {'args': (-1,), 'expected': False},
        {'args': (5,), 'expected': True},
    ],
    'is_sorted_asc': [
        {'args': ('hello',), 'expected': False},
        {'args': ('',), 'expected': True},
        {'args': ([1, 2, 3],), 'expected': True},
        {'args': ([],), 'expected': True},
    ],
    'is_sorted_desc': [
        {'args': ('hello',), 'expected': False},
        {'args': ('',), 'expected': True},
        {'args': ([1, 2, 3],), 'expected': False},
        {'args': ([],), 'expected': True},
    ],
    'is_subset': [
        {'args': ('a', 'b'), 'expected': False},
        {'args': ('hello', 'world'), 'expected': False},
        {'args': ([1, 2], [3, 4]), 'expected': False},
        {'args': ([], []), 'expected': True},
    ],
    'is_triangular': [
        {'args': (0,), 'expected': True},
        {'args': (1,), 'expected': True},
        {'args': (5,), 'expected': False},
    ],
    'is_upper': [
        {'args': ('hello',), 'expected': False},
        {'args': ('',), 'expected': False},
    ],
    'join_words': [
        {'args': ('a', 'b'), 'expected': 'a'},
        {'args': ('hello', 'world'), 'expected': 'hworldeworldlworldlworldo'},
    ],
    'kg_to_lbs': [
        {'args': (0,), 'expected': 0.0, 'approx': True},
        {'args': (1,), 'expected': 2.20462, 'approx': True},
        {'args': (-1,), 'expected': -2.20462, 'approx': True},
        {'args': (5,), 'expected': 11.0231, 'approx': True},
    ],
    'last_char': [
        {'args': (0,), 'expected': ''},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': ''},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': ''},
    ],
    'last_element': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'last_index': [
        {'args': ('a', 'b'), 'expected': -1},
        {'args': ('hello', 'world'), 'expected': -1},
        {'args': ([1, 2], [3, 4]), 'expected': -1},
        {'args': ([], []), 'expected': -1},
    ],
    'last_word': [
        {'args': ('hello',), 'expected': 'hello'},
        {'args': ('',), 'expected': ''},
    ],
    'least_frequent': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'linked_list_reverse': [
        {'args': ('hello',), 'expected': 'olleh'},
        {'args': ('',), 'expected': ''},
        {'args': ([1, 2, 3],), 'expected': [3, 2, 1]},
        {'args': ([],), 'expected': []},
    ],
    'list_length': [
        {'args': ('hello',), 'expected': 5},
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': 0},
    ],
    'longest_common_prefix': [
        {'args': ('a', 'b'), 'expected': ''},
        {'args': ('hello', 'world'), 'expected': ''},
        {'args': ([1, 2], [3, 4]), 'expected': []},
        {'args': ([], []), 'expected': []},
    ],
    'matrix_determinant': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'matrix_determinant_2x2': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'matrix_determinant_3x3': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'max_depth': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'max_of_list': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'max_of_many': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'max_of_three': [
        {'args': (1, 2, 3), 'expected': 3},
        {'args': (0, 0, 0), 'expected': 0},
        {'args': (5, 3, 1), 'expected': 5},
        {'args': (10, 2, 8), 'expected': 10},
    ],
    'max_row_sums': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'max_sliding_window_deque': [
        {'args': (0, 0), 'expected': 0},
        {'args': (1, 1), 'expected': 1},
        {'args': (2, 3), 'expected': 3},
        {'args': (5, 2), 'expected': 5},
        {'args': ('a', 'b'), 'expected': 'b'},
    ],
    'max_two': [
        {'args': (0, 0), 'expected': 0},
        {'args': (1, 1), 'expected': 1},
        {'args': (2, 3), 'expected': 3},
        {'args': (5, 2), 'expected': 5},
        {'args': ('a', 'b'), 'expected': 'b'},
    ],
    'mean_list': [
        {'args': (0,), 'expected': 0},
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 2.0, 'approx': True},
        {'args': ([],), 'expected': 0},
    ],
    'median_list': [
        {'args': ('hello',), 'expected': 'l'},
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 2},
        {'args': ([],), 'expected': 0},
    ],
    'merge_k_sorted_arrays': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'merge_k_sorted_lists': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'merge_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'merge_sort_inplace': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'merge_sorted_simple': [
        {'args': ('a', 'b'), 'expected': ['a', 'b']},
        {'args': ('hello', 'world'), 'expected': ['d', 'e', 'h', 'l', 'l', 'l', 'o', 'o', 'r', 'w']},
        {'args': ([1, 2], [3, 4]), 'expected': [1, 2, 3, 4]},
        {'args': ([], []), 'expected': []},
    ],
    'miles_to_km': [
        {'args': (0,), 'expected': 0.0, 'approx': True},
        {'args': (1,), 'expected': 1.60934, 'approx': True},
        {'args': (-1,), 'expected': -1.60934, 'approx': True},
        {'args': (5,), 'expected': 8.0467, 'approx': True},
    ],
    'min_depth': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'min_of_list': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'min_of_many': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'min_of_three': [
        {'args': (1, 2, 3), 'expected': 1},
        {'args': (0, 0, 0), 'expected': 0},
        {'args': (5, 3, 1), 'expected': 1},
        {'args': (10, 2, 8), 'expected': 2},
    ],
    'min_stack': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'min_two': [
        {'args': (0, 0), 'expected': 0},
        {'args': (1, 1), 'expected': 1},
        {'args': (2, 3), 'expected': 2},
        {'args': (5, 2), 'expected': 2},
        {'args': ('a', 'b'), 'expected': 'a'},
    ],
    'min_window_substring': [
        {'args': (0, 0), 'expected': 0},
        {'args': (1, 1), 'expected': 1},
        {'args': (2, 3), 'expected': 2},
        {'args': (5, 2), 'expected': 2},
        {'args': ('a', 'b'), 'expected': 'a'},
    ],
    'minimal_rotation': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'minutes_to_seconds': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'mirror_list': [
        {'args': ('hello',), 'expected': 'helloolleh'},
        {'args': ('',), 'expected': ''},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3, 3, 2, 1]},
        {'args': ([],), 'expected': []},
    ],
    'missing_number': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 0},
        {'args': ([],), 'expected': 0},
    ],
    'mod': [
        {'args': (1, 1), 'expected': 0},
        {'args': (2, 3), 'expected': 2},
        {'args': (5, 2), 'expected': 1},
    ],
    'mode_list': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'l'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'most_frequent': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'l'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'move_zeros': [
        {'args': ('hello',), 'expected': ['h', 'e', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'odd_even_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'offset_list': [
        {'args': ('a', 'b'), 'expected': ['ab']},
        {'args': ('hello', 'world'), 'expected': ['hworld', 'eworld', 'lworld', 'lworld', 'oworld']},
        {'args': ([], []), 'expected': []},
    ],
    'pairwise_product': [
        {'args': ([1, 2], [3, 4]), 'expected': [3, 8]},
        {'args': ([], []), 'expected': []},
    ],
    'pairwise_sum': [
        {'args': ('a', 'b'), 'expected': ['ab']},
        {'args': ('hello', 'world'), 'expected': ['hw', 'eo', 'lr', 'll', 'od']},
        {'args': ([1, 2], [3, 4]), 'expected': [4, 6]},
        {'args': ([], []), 'expected': []},
    ],
    'palindrome_partitioning_min': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'pancake_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'pigeonhole_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'pow': [
        {'args': (0, 0), 'expected': 1},
        {'args': (1, 1), 'expected': 1},
        {'args': (2, 3), 'expected': 8},
        {'args': (5, 2), 'expected': 25},
    ],
    'product_list': [
        {'args': (0,), 'expected': 1},
        {'args': ('',), 'expected': 1},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 1},
    ],
    'quick_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'quick_sort_hoare': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'quick_sort_lomuto': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'quick_sort_median3': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'quick_sort_randomized': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'radix_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'radix_sort_lsd': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'radix_sort_msd': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'range_list': [
        {'args': (0,), 'expected': 0},
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 2},
        {'args': ([],), 'expected': 0},
    ],
    'rectangle_area': [
        {'args': (0, 0), 'expected': 0},
        {'args': (1, 1), 'expected': 1},
        {'args': (2, 3), 'expected': 6},
        {'args': (5, 2), 'expected': 10},
    ],
    'rectangle_perimeter': [
        {'args': (0, 0), 'expected': 0},
        {'args': (1, 1), 'expected': 4},
        {'args': (2, 3), 'expected': 10},
        {'args': (5, 2), 'expected': 14},
        {'args': ('a', 'b'), 'expected': 'abab'},
    ],
    'reduce_max': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'reduce_min': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'reduce_product': [
        {'args': (0,), 'expected': 1},
        {'args': ('',), 'expected': 1},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 1},
    ],
    'reduce_sum': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'remove_digits': [
        {'args': ('hello',), 'expected': 'hello'},
        {'args': ('',), 'expected': ''},
        {'args': ([],), 'expected': ''},
    ],
    'remove_duplicates_sorted': [
        {'args': ('hello',), 'expected': ['h', 'e', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'remove_punctuation': [
        {'args': ('hello',), 'expected': 'hello'},
        {'args': ('',), 'expected': ''},
        {'args': ([],), 'expected': ''},
    ],
    'remove_vowels': [
        {'args': ('hello',), 'expected': 'hll'},
        {'args': ('',), 'expected': ''},
        {'args': ([],), 'expected': ''},
    ],
    'repeat_char': [
        {'args': (0, 0), 'expected': 0},
        {'args': (1, 1), 'expected': 1},
        {'args': (2, 3), 'expected': 6},
        {'args': (5, 2), 'expected': 10},
    ],
    'repeat_string': [
        {'args': (0, 0), 'expected': 0},
        {'args': (1, 1), 'expected': 1},
        {'args': (2, 3), 'expected': 6},
        {'args': (5, 2), 'expected': 10},
    ],
    'reverse_each_word': [
        {'args': ('hello',), 'expected': 'olleh'},
        {'args': ('',), 'expected': ''},
    ],
    'reverse_list_copy': [
        {'args': ('hello',), 'expected': 'olleh'},
        {'args': ('',), 'expected': ''},
        {'args': ([1, 2, 3],), 'expected': [3, 2, 1]},
        {'args': ([],), 'expected': []},
    ],
    'reverse_recursive': [
        {'args': ('hello',), 'expected': 'olleh'},
        {'args': ('',), 'expected': ''},
        {'args': ([1, 2, 3],), 'expected': [3, 2, 1]},
        {'args': ([],), 'expected': []},
    ],
    'reverse_slice': [
        {'args': ('hello',), 'expected': 'olleh'},
        {'args': ('',), 'expected': ''},
        {'args': ([1, 2, 3],), 'expected': [3, 2, 1]},
        {'args': ([],), 'expected': []},
    ],
    'reverse_string': [
        {'args': ('hello',), 'expected': 'olleh'},
        {'args': ('',), 'expected': ''},
        {'args': ([1, 2, 3],), 'expected': [3, 2, 1]},
        {'args': ([],), 'expected': []},
    ],
    'reverse_words': [
        {'args': ('hello',), 'expected': 'hello'},
        {'args': ('',), 'expected': ''},
    ],
    'scale_list': [
        {'args': ([1, 2], [3, 4]), 'expected': [[3, 4], [3, 4, 3, 4]]},
        {'args': ([], []), 'expected': []},
    ],
    'second_largest': [
        {'args': ('hello',), 'expected': 'l'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 2},
        {'args': ([],), 'expected': None},
    ],
    'second_smallest': [
        {'args': ('hello',), 'expected': 'h'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 2},
        {'args': ([],), 'expected': None},
    ],
    'seconds_to_minutes': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'selection_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'selection_sort_stable': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'set_difference': [
        {'args': ('a', 'b'), 'expected': ['a']},
        {'args': ('hello', 'world'), 'expected': ['e', 'h']},
        {'args': ([1, 2], [3, 4]), 'expected': [1, 2]},
        {'args': ([], []), 'expected': []},
    ],
    'set_intersection': [
        {'args': ('a', 'b'), 'expected': []},
        {'args': ('hello', 'world'), 'expected': ['o', 'l']},
        {'args': ([1, 2], [3, 4]), 'expected': []},
        {'args': ([], []), 'expected': []},
    ],
    'set_symmetric_difference': [
        {'args': ('a', 'b'), 'expected': ['b', 'a']},
        {'args': ('hello', 'world'), 'expected': ['e', 'r', 'd', 'w', 'h']},
        {'args': ([1, 2], [3, 4]), 'expected': [1, 2, 3, 4]},
        {'args': ([], []), 'expected': []},
    ],
    'set_union': [
        {'args': ('a', 'b'), 'expected': ['b', 'a']},
        {'args': ('hello', 'world'), 'expected': ['r', 'l', 'h', 'e', 'o', 'd', 'w']},
        {'args': ([1, 2], [3, 4]), 'expected': [1, 2, 3, 4]},
        {'args': ([], []), 'expected': []},
    ],
    'shell_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'sliding_window_max': [
        {'args': (0, 0), 'expected': 0},
        {'args': (1, 1), 'expected': 1},
        {'args': (2, 3), 'expected': 3},
        {'args': (5, 2), 'expected': 5},
        {'args': ('a', 'b'), 'expected': 'b'},
    ],
    'smoothsort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'snake_to_camel': [
        {'args': ('hello',), 'expected': 'hello'},
        {'args': ('',), 'expected': ''},
    ],
    'sort_descending': [
        {'args': ('hello',), 'expected': ['o', 'l', 'l', 'h', 'e']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [3, 2, 1]},
        {'args': ([],), 'expected': []},
    ],
    'sort_dict_by_key': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'sort_dict_by_value': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'sort_simple': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'sphere_volume': [
        {'args': (0,), 'expected': 0.0, 'approx': True},
        {'args': (1,), 'expected': 4.1887902047863905, 'approx': True},
        {'args': (-1,), 'expected': -4.1887902047863905, 'approx': True},
        {'args': (5,), 'expected': 523.5987755982989, 'approx': True},
    ],
    'split_csv': [
        {'args': ('hello',), 'expected': ['hello']},
        {'args': ('',), 'expected': ['']},
    ],
    'split_lines': [
        {'args': ('hello',), 'expected': ['hello']},
        {'args': ('',), 'expected': ['']},
    ],
    'stack_max': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'o'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': None},
    ],
    'stack_min': [
        {'args': (0,), 'expected': None},
        {'args': ('hello',), 'expected': 'e'},
        {'args': ('',), 'expected': None},
        {'args': ([1, 2, 3],), 'expected': 1},
        {'args': ([],), 'expected': None},
    ],
    'stack_reverse': [
        {'args': ('hello',), 'expected': 'olleh'},
        {'args': ('',), 'expected': ''},
        {'args': ([1, 2, 3],), 'expected': [3, 2, 1]},
        {'args': ([],), 'expected': []},
    ],
    'stack_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'starts_with': [
        {'args': ('a', 'b'), 'expected': False},
        {'args': ('hello', 'world'), 'expected': False},
    ],
    'std_dev_list': [
        {'args': (0,), 'expected': 0},
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 0.816496580927726, 'approx': True},
        {'args': ([],), 'expected': 0},
    ],
    'stooge_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'strip_extra_spaces': [
        {'args': ('hello',), 'expected': 'hello'},
        {'args': ('',), 'expected': ''},
    ],
    'sum_cols': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'sum_matrix': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'sum_of_many': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'sum_recursive': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'sum_rows': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'swap_case': [
        {'args': ('hello',), 'expected': 'HELLO'},
        {'args': ('',), 'expected': ''},
    ],
    'three_sum': [
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 6},
        {'args': ([],), 'expected': 0},
    ],
    'tim_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'tim_sort_simple': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'to_capitalize': [
        {'args': ('hello',), 'expected': 'Hello'},
        {'args': ('',), 'expected': ''},
    ],
    'to_celsius': [
        {'args': (0,), 'expected': -17.77777777777778, 'approx': True},
        {'args': (1,), 'expected': -17.22222222222222, 'approx': True},
        {'args': (-1,), 'expected': -18.333333333333332, 'approx': True},
        {'args': (5,), 'expected': -15.0, 'approx': True},
    ],
    'to_fahrenheit': [
        {'args': (0,), 'expected': 32.0, 'approx': True},
        {'args': (1,), 'expected': 33.8, 'approx': True},
        {'args': (-1,), 'expected': 30.2, 'approx': True},
        {'args': (5,), 'expected': 41.0, 'approx': True},
    ],
    'to_hex': [
        {'args': (0,), 'expected': '0'},
        {'args': (1,), 'expected': '1'},
        {'args': (-1,), 'expected': 'x1'},
        {'args': (5,), 'expected': '5'},
    ],
    'to_octal': [
        {'args': (0,), 'expected': '0'},
        {'args': (1,), 'expected': '1'},
        {'args': (-1,), 'expected': 'o1'},
        {'args': (5,), 'expected': '5'},
    ],
    'to_reversed_list': [
        {'args': ('hello',), 'expected': 'olleh'},
        {'args': ('',), 'expected': ''},
        {'args': ([1, 2, 3],), 'expected': [3, 2, 1]},
        {'args': ([],), 'expected': []},
    ],
    'to_sorted_list': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'to_title': [
        {'args': ('hello',), 'expected': 'Hello'},
        {'args': ('',), 'expected': ''},
    ],
    'topological_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'topological_sort_deps': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'tournament_sort': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'unique_count': [
        {'args': ('hello',), 'expected': 4},
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 3},
        {'args': ([],), 'expected': 0},
    ],
    'unique_sorted': [
        {'args': ('hello',), 'expected': ['e', 'h', 'l', 'o']},
        {'args': ('',), 'expected': []},
        {'args': ([1, 2, 3],), 'expected': [1, 2, 3]},
        {'args': ([],), 'expected': []},
    ],
    'variance_list': [
        {'args': (0,), 'expected': 0},
        {'args': ('',), 'expected': 0},
        {'args': ([1, 2, 3],), 'expected': 0.6666666666666666, 'approx': True},
        {'args': ([],), 'expected': 0},
    ],
    'zip_lists': [
        {'args': ('a', 'b'), 'expected': [('a', 'b')]},
        {'args': ('hello', 'world'), 'expected': [('h', 'w'), ('e', 'o'), ('l', 'r'), ('l', 'l'), ('o', 'd')]},
        {'args': ([1, 2], [3, 4]), 'expected': [(1, 3), (2, 4)]},
        {'args': ([], []), 'expected': []},
    ],
}
