"""Download a curated subset of The Stack v2 for pretraining a coding LLM.

Streams bigcode/the-stack-v2-train, filters by language and size, and writes
JSONL shards (~500 MB each) to research/data/pretrain/the_stack_v2/.

Output format (one JSON object per line):
    {"text": "<code>", "language": "python", "name": "foo.py"}

Usage:
    set PYTHONPATH=D:\\windsurf\\ForgeAI
    D:\\windsurf\\ForgeAI\\venv\\Scripts\\python.exe research\\data\\pretrain\\download_stack_v2.py
"""
from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

# ── Config ──────────────────────────────────────────────────────────────────

OUTPUT_DIR = Path(r"D:\windsurf\ForgeAI\research\data\pretrain\the_stack_v2")
SHARD_PREFIX = "stack_v2"
SHARD_MAX_BYTES = 500 * 1024 * 1024          # 500 MB per file
TARGET_TOTAL_BYTES = 5 * 1024 * 1024 * 1024  # 5 GB total
MIN_CHARS = 100
MAX_BYTES = 50 * 1024                        # 50 KB
LANGUAGES = {"python", "javascript", "typescript", "rust", "go", "cpp", "java"}
PROGRESS_EVERY = 10_000

# HF dataset
DATASET_ID = "bigcode/the-stack-v2-train"
SPLIT = "train"

# Map from dataset language field values to our canonical names
LANG_ALIASES = {
    "python": "python",
    "javascript": "javascript",
    "typescript": "typescript",
    "rust": "rust",
    "go": "go",
    "c++": "cpp",
    "cpp": "cpp",
    "c": "cpp",          # include plain C under cpp bucket
    "java": "java",
}

# ── Helpers ─────────────────────────────────────────────────────────────────


def _load_env() -> None:
    """Load HF token from .env if present."""
    env_path = Path(__file__).resolve().parents[3] / ".env"
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    os.environ[k.strip()] = v.strip()
    os.environ.setdefault("PYTHONUTF8", "1")


def is_generated_or_minified(content: str) -> bool:
    """Return True if the first line suggests generated/minified code."""
    if not content:
        return False
    first_line = content.split("\n", 1)[0].lower()[:200]
    markers = [
        "generated",
        "auto-generated",
        "autogenerated",
        "do not edit",
        "this file was automatically generated",
        "minified",
        "webpack",
        "sourceMappingURL",
        "/*!",
        "// @license",
    ]
    return any(m in first_line for m in markers)


def get_language(ex: dict) -> str | None:
    """Extract and normalise the language field from a dataset example."""
    lang = ex.get("language")
    if not lang:
        return None
    lang = lang.strip().lower()
    return LANG_ALIASES.get(lang)


def get_content(ex: dict) -> str | None:
    """Extract the raw source code content from a dataset example."""
    # The Stack v2 stores code in the 'content' field
    content = ex.get("content")
    if content is None:
        # Fallbacks seen in some HF code datasets
        content = ex.get("code") or ex.get("text")
    if content is None:
        return None
    if not isinstance(content, str):
        return None
    return content


def get_filename(ex: dict) -> str:
    """Extract the filename from a dataset example."""
    name = ex.get("name") or ex.get("filename") or ex.get("path") or ""
    if isinstance(name, list) and name:
        name = name[-1]
    return str(name) if name else "unknown"


# ── Main download loop ──────────────────────────────────────────────────────


def run() -> None:
    _load_env()

    # Import datasets (heavy import, do after env setup)
    import datasets

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print(f"[stack_v2] Loading {DATASET_ID} (streaming=True) ...", flush=True)
    token = os.environ.get("HF_TOKEN", "")
    ds = datasets.load_dataset(DATASET_ID, split=SPLIT, streaming=True,
                               token=token if token else None)

    shard_idx = 0
    shard_path = OUTPUT_DIR / f"{SHARD_PREFIX}_{shard_idx:02d}.jsonl"
    shard_fh = open(shard_path, "w", encoding="utf-8")
    shard_bytes = 0

    total_bytes = 0
    total_files = 0
    skipped_size = 0
    skipped_lang = 0
    skipped_gen = 0
    skipped_empty = 0

    lang_counts: dict[str, int] = {}
    lang_bytes: dict[str, int] = {}

    t0 = time.time()

    for ex in ds:
        # ── Language filter ──
        lang = get_language(ex)
        if lang is None:
            skipped_lang += 1
            continue

        # ── Content extraction ──
        content = get_content(ex)
        if content is None:
            skipped_empty += 1
            continue

        # ── Size filters ──
        content_bytes = len(content.encode("utf-8"))
        if content_bytes > MAX_BYTES:
            skipped_size += 1
            continue
        if len(content) < MIN_CHARS:
            skipped_size += 1
            continue

        # ── Generated / minified filter ──
        if is_generated_or_minified(content):
            skipped_gen += 1
            continue

        # ── Write record ──
        name = get_filename(ex)
        record = {"text": content, "language": lang, "name": name}
        line = json.dumps(record, ensure_ascii=False) + "\n"
        line_bytes = len(line.encode("utf-8"))

        shard_fh.write(line)
        shard_bytes += line_bytes
        total_bytes += line_bytes
        total_files += 1

        lang_counts[lang] = lang_counts.get(lang, 0) + 1
        lang_bytes[lang] = lang_bytes.get(lang, 0) + line_bytes

        # ── Shard rotation ──
        if shard_bytes >= SHARD_MAX_BYTES:
            shard_fh.close()
            print(
                f"[stack_v2] Closed shard {shard_idx:02d} "
                f"({shard_bytes / 1e6:.1f} MB)",
                flush=True,
            )
            shard_idx += 1
            shard_path = OUTPUT_DIR / f"{SHARD_PREFIX}_{shard_idx:02d}.jsonl"
            shard_fh = open(shard_path, "w", encoding="utf-8")
            shard_bytes = 0

        # ── Progress ──
        if total_files % PROGRESS_EVERY == 0:
            elapsed = time.time() - t0
            mb = total_bytes / 1e6
            rate = mb / elapsed if elapsed > 0 else 0
            pct = total_bytes / TARGET_TOTAL_BYTES * 100
            print(
                f"[stack_v2] {total_files:,} files | {mb:.0f} MB "
                f"({pct:.1f}% of target) | {rate:.1f} MB/s | "
                f"skipped: lang={skipped_lang:,} size={skipped_size:,} "
                f"gen={skipped_gen:,} empty={skipped_empty:,} | "
                f"shard={shard_idx:02d}",
                flush=True,
            )

        # ── Stop at target ──
        if total_bytes >= TARGET_TOTAL_BYTES:
            print(
                f"[stack_v2] Reached target {TARGET_TOTAL_BYTES / 1e9:.1f} GB, stopping.",
                flush=True,
            )
            break

    # ── Cleanup ──
    shard_fh.close()
    # Remove trailing empty shard if nothing was written to it
    if shard_bytes == 0 and shard_idx > 0:
        try:
            shard_path.unlink()
        except OSError:
            pass

    elapsed = time.time() - t0

    # ── Report ──
    print("\n" + "=" * 70)
    print("DOWNLOAD COMPLETE — The Stack v2 subset")
    print("=" * 70)
    print(f"Total files written : {total_files:,}")
    print(f"Total size          : {total_bytes / 1e9:.2f} GB")
    print(f"Shards written      : {shard_idx + (1 if shard_bytes > 0 else 0)}")
    print(f"Elapsed time        : {elapsed / 60:.1f} min")
    print()
    print("Skipped:")
    print(f"  Wrong language    : {skipped_lang:,}")
    print(f"  Size out of range : {skipped_size:,}")
    print(f"  Generated/minified: {skipped_gen:,}")
    print(f"  Empty/no content  : {skipped_empty:,}")
    print()
    print("Language breakdown:")
    print(f"  {'Language':<14} {'Files':>10} {'Size (MB)':>12}")
    print(f"  {'-'*14} {'-'*10} {'-'*12}")
    for lang in sorted(lang_counts, key=lambda l: lang_bytes[l], reverse=True):
        count = lang_counts[lang]
        mb = lang_bytes[lang] / 1e6
        print(f"  {lang:<14} {count:>10,} {mb:>12.1f}")
    print()
    print("Output files:")
    for f in sorted(OUTPUT_DIR.glob(f"{SHARD_PREFIX}_*.jsonl")):
        sz = f.stat().st_size
        print(f"  {f.name:<30} {sz / 1e6:>10.1f} MB")
    print("=" * 70)


if __name__ == "__main__":
    run()
