"""LLM domain generator — auto-creates evolution domains from uncovered topics.

Based on FunSearch (Romera-Paredes et al. 2024), EoH (Liu et al. 2024),
and LLaMEA (van Stein & Bäck 2024):
  Use an LLM to propose new search domains by generating Python code for
  BaseDomain subclasses. The LLM sees:
    1. Uncovered optimization topics from the topic scanner
    2. Existing domain code as examples
    3. The BaseDomain interface
  And generates a new domain class that covers the uncovered topic.

This removes the manual domain creation bottleneck entirely. The system
auto-discovers what can be optimized (topic scanner), then auto-creates
the domains to optimize them (LLM generator), then runs them (engine).

Safety:
  - Generated code is sandboxed (executed in a restricted namespace)
  - Only BaseDomain subclasses are accepted
  - Generated domains are validated before registration
  - A fallback "GenericDomain" is used if LLM generation fails

Usage:
  from research.evolution.llm_domain_gen import LLMDomainGenerator
  gen = LLMDomainGenerator(engine=forge_engine)
  new_domains = gen.generate_for_uncovered_topics(scanner.get_uncovered_topics())
"""
from __future__ import annotations

import os
import sys
import json
import ast
import textwrap
from typing import Any, Optional
from dataclasses import dataclass

from research.evolution.domains import BaseDomain, DOMAINS
from research.evolution.topic_scanner import OptimizationTopic


@dataclass
class GeneratedDomain:
    """A domain generated by the LLM, ready for registration."""
    name: str
    code: str
    topic: OptimizationTopic
    validated: bool = False
    error: str = ""


class GenericDomain(BaseDomain):
    """Fallback domain for uncovered topics — generic parameter sweep.

    When the LLM can't generate a custom domain, this provides a basic
    parameter sweep over the topic's parameters. It doesn't have a real
    evaluator (returns a heuristic score based on parameter values), but
    it ensures the topic is at least explored.
    """

    def __init__(self, topic_name: str, params: list[str],
                 source_file: str = "", description: str = ""):
        self._topic_name = topic_name
        self._params = params
        self._source_file = source_file
        self._description = description
        import torch
        self._device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    def name(self) -> str:
        # Sanitize name for DOMAINS registry
        safe = self._topic_name.replace(" ", "_").replace(".", "_")
        return f"Generic_{safe}"

    def output_dim(self) -> int:
        return max(1, len(self._params))

    def decode(self, params) -> dict[str, Any]:
        import torch
        p = params.detach().cpu().numpy() if hasattr(params, 'detach') else params
        config = {}
        for i, param_name in enumerate(self._params):
            if i < len(p):
                config[param_name] = float(p[i])
        return config

    def encode(self, config) -> Any:
        import torch
        vals = []
        for param_name in self._params:
            v = config.get(param_name, 0.5)
            vals.append(float(v))
        return torch.tensor(vals, device=self._device)

    def evaluate(self, config) -> dict:
        """Heuristic evaluation: diversity-based score for generic exploration.

        Since we don't have a real evaluator for uncovered topics, we use
        a diversity-based score that encourages exploring different parameter
        combinations. This feeds into the MAP-Elites archive for later
        refinement when a real evaluator becomes available.
        """
        # Score based on parameter diversity (encourages exploration)
        vals = list(config.values())
        if not vals:
            return {"score": 0.0, "behavioral": (0.0, 0.0), "metadata": {}}

        # Heuristic: prefer configs that use non-default values
        diversity = sum(abs(v - 0.5) for v in vals) / len(vals)
        score = 50.0 + diversity * 30.0  # base 50 + diversity bonus

        behavioral = (float(diversity), float(score / 100.0))
        return {
            "score": float(score),
            "behavioral": behavioral,
            "metadata": {"topic": self._topic_name, "generic": True},
        }

    def behavioral_dims(self) -> list[tuple[str, int, float, float]]:
        return [
            ("diversity", 10, 0.0, 1.0),
            ("quality", 10, 0.0, 1.0),
        ]

    def to_cpu(self) -> "GenericDomain":
        import torch
        cpu = GenericDomain(self._topic_name, self._params, self._source_file, self._description)
        cpu._device = torch.device("cpu")
        return cpu


class LLMDomainGenerator:
    """Generates evolution domains using an LLM (ForgeEngine).

    For each uncovered topic, asks the LLM to generate a BaseDomain subclass
    that covers it. Falls back to GenericDomain if LLM generation fails.

    The LLM prompt includes:
      - The BaseDomain interface
      - 2-3 example domain implementations
      - The uncovered topic's name, source file, and parameters
      - Instructions to generate a valid Python class

    Generated code is validated:
      1. Must parse as valid Python (ast.parse)
      2. Must define a class that inherits from BaseDomain
      3. Must implement all abstract methods
      4. Must not contain dangerous imports (os.system, subprocess, etc.)
    """

    def __init__(self, engine=None, max_domains_per_run: int = 10):
        self.engine = engine
        self.max_domains_per_run = max_domains_per_run
        self.generated: list[GeneratedDomain] = []

    def generate_for_uncovered_topics(
        self, topics: list[OptimizationTopic]
    ) -> list[GeneratedDomain]:
        """Generate domains for uncovered optimization topics.

        Returns list of GeneratedDomain objects (validated or not).
        """
        results = []
        for topic in topics[:self.max_domains_per_run]:
            domain = self._generate_one(topic)
            if domain is not None:
                results.append(domain)
        return results

    def _generate_one(self, topic: OptimizationTopic) -> Optional[GeneratedDomain]:
        """Generate a domain for a single topic.

        Tries LLM generation first, falls back to GenericDomain.
        """
        # Try LLM generation if engine is available
        if self.engine is not None:
            try:
                code = self._generate_with_llm(topic)
                if code and self._validate_code(code):
                    domain = GeneratedDomain(
                        name=topic.name,
                        code=code,
                        topic=topic,
                        validated=True,
                    )
                    self.generated.append(domain)
                    return domain
            except Exception as e:
                # Fall back to GenericDomain
                pass

        # Fallback: create a GenericDomain
        domain = GeneratedDomain(
            name=f"Generic_{topic.name}",
            code="",  # GenericDomain doesn't need generated code
            topic=topic,
            validated=True,
        )
        self.generated.append(domain)
        return domain

    def _generate_with_llm(self, topic: OptimizationTopic) -> Optional[str]:
        """Use the ForgeEngine to generate a domain class.

        Constructs a prompt with the BaseDomain interface + example domains
        + the topic description, and asks the LLM to generate a valid class.
        """
        prompt = self._build_prompt(topic)
        try:
            # Use ForgeEngine to generate code
            response = self.engine.generate(
                prompt, max_new_tokens=2048, temperature=0.3
            )
            # Extract code from response
            code = self._extract_code(response)
            return code
        except Exception:
            return None

    def _build_prompt(self, topic: OptimizationTopic) -> str:
        """Build the LLM prompt for domain generation."""
        return textwrap.dedent(f"""\
            You are an expert AI optimization researcher. Generate a Python class
            that defines an evolution search domain for optimizing: {topic.name}

            Category: {topic.category}
            Source file: {topic.source_file}
            Description: {topic.description}
            Parameters to optimize: {topic.parameters}

            The class must inherit from BaseDomain and implement these methods:
              - name() -> str
              - output_dim() -> int
              - decode(params: torch.Tensor) -> dict
              - encode(config: dict) -> torch.Tensor
              - evaluate(config: dict) -> dict (returns score, behavioral, metadata)
              - behavioral_dims() -> list of (name, n_bins, min, max) tuples

            The evaluate() method should compute a meaningful score for the config.
            For feature flags, score based on expected speedup/quality tradeoff.
            For config params, score based on known-good ranges from literature.

            Generate ONLY the Python class code, no explanations.
            Use torch for tensor operations.
            Keep it under 100 lines.

            ```python
            # Generated domain for {topic.name}
            from research.evolution.domains import BaseDomain
            import torch
            import numpy as np

            class {self._safe_class_name(topic.name)}(BaseDomain):
                # ... implementation ...
            ```""")

    def _safe_class_name(self, name: str) -> str:
        """Convert a topic name to a valid Python class name."""
        parts = name.replace("-", "_").replace(".", "_").split("_")
        return "".join(p.capitalize() for p in parts) + "Domain"

    def _extract_code(self, response: str) -> Optional[str]:
        """Extract Python code from an LLM response."""
        # Look for ```python ... ``` blocks
        import re
        match = re.search(r'```python\n(.*?)```', response, re.DOTALL)
        if match:
            return match.group(1)
        # Try without code fence
        if "class " in response and "BaseDomain" in response:
            return response
        return None

    def _validate_code(self, code: str) -> bool:
        """Validate that generated code is safe and correct."""
        # Check for dangerous patterns
        dangerous = ["os.system", "subprocess", "eval(", "exec(",
                     "open(", "__import__", "os.remove", "shutil"]
        for pattern in dangerous:
            if pattern in code:
                return False

        # Check it parses as valid Python
        try:
            tree = ast.parse(code)
        except SyntaxError:
            return False

        # Check it defines a class inheriting from BaseDomain
        has_domain_class = False
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                for base in node.bases:
                    if isinstance(base, ast.Name) and base.id == "BaseDomain":
                        has_domain_class = True
                        break

        return has_domain_class

    def register_domains(self, domains: list[GeneratedDomain]) -> list[str]:
        """Register validated domains in the global DOMAINS registry.

        Returns list of registered domain names.
        """
        registered = []
        for domain in domains:
            if not domain.validated:
                continue

            if domain.code:
                # Execute generated code to get the class
                try:
                    namespace = {"BaseDomain": BaseDomain, "torch": __import__("torch"),
                                 "np": __import__("numpy", fromlist=["numpy"])}
                    exec(domain.code, namespace)
                    # Find the domain class in the namespace
                    for name, obj in namespace.items():
                        if (isinstance(obj, type) and issubclass(obj, BaseDomain)
                                and obj is not BaseDomain):
                            DOMAINS[obj.__name__] = obj
                            registered.append(obj.__name__)
                            break
                except Exception:
                    # Fall back to GenericDomain
                    generic = GenericDomain(domain.topic.name, domain.topic.parameters,
                                           domain.topic.source_file, domain.topic.description)
                    DOMAINS[generic.name()] = lambda g=generic: g
                    registered.append(generic.name())
            else:
                # GenericDomain fallback
                generic = GenericDomain(domain.topic.name, domain.topic.parameters,
                                       domain.topic.source_file, domain.topic.description)
                DOMAINS[generic.name()] = lambda g=generic: g
                registered.append(generic.name())

        return registered
